### ISSUE TITLE
It's not possible to send POST data

### ISSUE THREAD

**Issue by tomnomnom** [tomnomnom/meg#13]
It's not currently possible to send data with POST, PUT request etc.

It would be nice to use `-d` like curl, but it's already taken by the request delay.

**Comment by cmbuckley** [comment]
Suggest request delay should be moved to `-w`/`--wait` to match wget. That's in seconds rather than ms, however.

**Comment by tomnomnom** [comment]
That's kind of tempting actually... But I don't like breaking backwards compatibility if possible. I'll sleep on it a bit
