### ISSUE TITLE
Support for single host

### ISSUE THREAD

**Issue by madaratech** [tomnomnom/meg#20]
Hi @tomnomnom, 

Thank you for actively developing this project, I would like to request minor improvement for this project.

Currently, **meg** supports suffix and prefix format, where we can feed both lists and it will process them accordingly, it would be nice and helpful for the quick test if we can feed **single host** as well along with existing option.   

Example:  
```
meg suffix http://example.com
```

Thank you.

**Comment by tomnomnom** [comment]
@madaratech great idea! I think that will make doing quick tests a lot easier.

I think it would be a good time to have a change of terminology before the project goes much further too.

I've been using the prefix/suffix terminology for a while now, but I don't think it's very descriptive. Do you think 'server' and 'path' is a good choice?

**Comment by madaratech** [comment]
Yeah, `prefix/suffix` is not very relatable to the project, anyway users going to use there own filename to feed, but in general terminology for this project, I would suggest, `path-list/host-list` or `path/host`.

Regards.

**Comment by tomnomnom** [comment]
The terminology change has been done in 8bfa2d02

I wanted to get that out of the way before doing this as it would have just been more code to change :D

**Comment by tomnomnom** [comment]
@madaratech while I remember: until this is implemented you can use a little bash trick to turn command output into a file descriptor and get the behaviour you want this way:

```
▶ meg -v /robots.txt <(echo https://example.com)
out/example.com/7c8443b50dd91de51d5f152effc9c70a45cc4e7c https://example.com/robots.txt (404 Not Found)
```
