### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by joerichard** [tomnomnom/meg#27]
Hello, 

I have a problem like this 

```
root@xxx:~/sf/megplus# go get github.com/tomnomnom/meg
# github.com/tomnomnom/rawhttp
/root/go/src/github.com/tomnomnom/rawhttp/request.go:102: u.Hostname undefined (
type *url.URL has no field or method Hostname)
/root/go/src/github.com/tomnomnom/rawhttp/request.go:103: u.Port undefined (type
 *url.URL has no field or method Port)
/root/go/src/github.com/tomnomnom/rawhttp/request.go:259: undefined: x509.System
CertPool
```

how to solve this?  Thanks.

**Comment by tomnomnom** [comment]
Hello!

It looks like you're using an old version of Go. If possible, try updating to a recent version like 1.9 or 1.10 :)

If that's not really possible, try a [binary release](https://github.com/tomnomnom/meg/releases) for your platform instead. Download the file for your platform and extract it, then move the binary to somewhere in your `$PATH` (e.g. into `/usr/bin/`).

Let me know if you have any more issues :)

**Comment by joerichard** [comment]
Hello, i'm using binary release now, it works great

Thanks!
