### ISSUE TITLE
Ability to optionally ignore https certificate errors

### ISSUE THREAD

**Issue by MikeRalphson** [tomnomnom/meg#28]
This would be useful when testing alternate host names / IP ranges.

**Comment by tomnomnom** [comment]
Hi @MikeRalphson! Thanks for raising and issue :)

This is actually the default behaviour of meg... That might seem like a bad idea, but given the tools intended use I think it's not too unreasonable.

Have you been hitting issues with invalid certificates?

**Comment by MikeRalphson** [comment]
Ah, no, I think then it was just a warning message? Thanks for clarifying.
