### ISSUE TITLE
Facing issue regarding opening paths file.

### ISSUE THREAD

**Issue by rudrasingh99** [tomnomnom/meg#31]
Hey,

I use go get to get a copy of meg.

But it's been showing me error failed to open paths file: file ./paths not found

**Comment by m0nk3y-s3c** [comment]
just happened to me too.
I had it working but I wanted to delete it and rebuild it.
now i get this error
before i deleted it, it worked fine.

wonder what can it be.
weird...

**Comment by deathflash1411** [comment]
I am having this same issue, how to fix it ?

**Comment by ricardoparro** [comment]
same issue here

**Comment by pusky-** [comment]
@tomnomnom

**Comment by dlopez** [comment]
For those looking for the solution to this.. Reading is essential. 

`Without any arguments, meg will read paths from a file called ./paths, and hosts from a file called ./hosts. There will also be no output:`

If you don't have those files, just create them. `touch paths && touch hosts`
