### ISSUE TITLE
Proxy Settings on Cygwin

### ISSUE THREAD

**Issue by riramar** [tomnomnom/meg#35]
Hi,

Thanks for amazing tool!
I'm in a cygwin environment behind a firewall and proxy.
The variables below seems not be working for me to use meg with a proxy.

```
export HTTP_PROXY="http://myproxy.com:8080";
export HTTPS_PROXY="http://myproxy.com:8080";
```

I was assuming that meg would load the proxy settings from OS variables above but it doesn't work.
Do you know how can I use meg in the situation described above?

**Comment by riramar** [comment]
Thanks! I fixed the issue.

**Comment by jaikishantulswani** [comment]
@riramar how you fixed this ?

**Comment by riramar** [comment]
OMG! This was long time ago and unfortunately I don't remember. :(
Sorry...

**Comment by jaikishantulswani** [comment]
@riramar I am also looking for the same to pipe the meg output through proxy
