### ISSUE TITLE
Multiple Headers

### ISSUE THREAD

**Issue by MMrhassel** [tomnomnom/meg#43]
_Hi, I wanted to test Host Header Injection with Multiple Headers but I found that only one hydride can be sent
Suggest that you add the possibility to send Multiple Headers_

**Comment by tomnomnom** [comment]
Hello!

Sending multiple headers is already possible by passing multiple `-H` options, like this:

![image](https://user-images.githubusercontent.com/58276/62242222-996be580-b3d2-11e9-9af7-919360b68d70.png)

^^^ In this example I request https://httpbin.org/anything which returns the headers sent to it in the response. Note that both custom headers from the request are returned. 

Let me know if you have any more issues

**Comment by MMrhassel** [comment]
Thank you very much
