### ISSUE TITLE
Issue with dependency rawhttp

### ISSUE THREAD

**Issue by fabaff** [tomnomnom/meg#67]
`meg` depends on `rawhttp`. `rawhttp` doesn't have a license. This is an issue as it makes it impossible to include `meg` into the Fedora Package Collection.

Simplest solution would be if @tomnomnom includes a license to `rawhttp` (see https://github.com/tomnomnom/rawhttp/issues/7). Otherwise, a switch to a different HTTP handler would be needed.

**Comment by tomnomnom** [comment]
This should be fixed now. Thanks!

**Comment by fabaff** [comment]
Thank you.

Also, submitted: https://bugzilla.redhat.com/show_bug.cgi?id=1840628
